name: CI (lint)

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "**/*.png"
      - "**/*.jpg"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "**/*.png"
      - "**/*.jpg"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -e .[dev]

      - name: Run Ruff + Black + Mypy
        run: |
          ruff check .
          ruff format --check .
          black --check .
          mypy src/
